// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MapPrototype.iOS.en.lproj
{
	public partial class MapController : UIView
	{
		public MapController (IntPtr handle) : base (handle)
		{
		}
	}
}
