// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MapPrototype.iOS
{
	public partial class TempControllerXH : UIViewController
	{
		public TempControllerXH (IntPtr handle) : base (handle)
		{
		}
	}
}
